# syntax=docker/dockerfile:1
FROM --platform=linux/amd64 python:3.10.7

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

WORKDIR /code
COPY . /code
RUN pip install -r requirements.txt
